

configs: 
  general: 
    tasks: [
      segmentation.threshold, 
      segmentation.local_threshold, 
      segmentation.meanshift, 
    ]

  image:
    filetype: [png, jpg, jpeg]
    # root: [
    #   os.path.join(configs.general.root, "images"), 
    #   configs.general.root, 
    # ] # Where to search images which are to be processed.

  # result: # Where to store images which are processed.
    # root: os.path.join(configs.general.root, "results")

  segmentation:
    method: meanshift #"local_threshold"
    threshold: 
      bins: 2
      thre: auto
      patches: [4, 4] # (num_rows, num_cols)
    meanshift: 
      kernel: Gaussian
      bandwidth: 16
      num_seeds: 10000
      tolerance: 5.0
      max_iters: 400
      speedup: false
      # patches: [4, 4] # (num_rows, num_cols)

  detection:
    edge: false
    corner: false

